=== apacha01/sapi/src/schemas/foods-schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "https://raw.githubusercontent.com/apacha01/sapi/master/src/schemas/foods-schema.json",
	"title": "Food",
	"type": "object",
	"required": [
		"name",
		"shop_tier",
		"sources",
		"effect",
		"perk",
		"sprites"
	],
	"properties": {
		"name": {
			"$id": "#food/name",
			"title": "Food ame",
			"type": "string"
		},
		"shop_tier": {
			"$id": "#food/shop_tier",
			"title": "Shop_tier",
			"description": "Food tier in shop.",
			"type": "object",
			"required": [
				"shop_tier",
				"url"
			],
			"properties": {
				"shop_tier": {
					"$id": "#food/shop_tier/shop_tier",
					"title": "Shop_tier",
					"description": "Food tier.",
					"type": "integer",
					"minimum": 1,
					"maximum": 6
				},
				"url": {
					"$id": "#food/shop_tier/url",
					"title": "Url",
					"description": "Food tier url.",
					"type": "string",
					"format": "uri"
				}
			}
		},
		"sources": {
			"$id": "#food/sources",
			"title": "Sources",
			"description": "List of sources (how to get it) for this food.",
			"type": "array",
			"items": {
				"$id": "#food/sources/items",
				"title": "Source",
				"description": "A possible source to obtain this food.",
				"type": "object",
				"required": [
					"source",
					"url"
				],
				"properties": {
					"source": {
						"$id": "#food/sources/items/source",
						"title": "Source",
						"description": "The description on how/where to obtain this food.",
						"type": "string"
					},
					"url": {
						"$id": "#food/sources/items/url",
						"title": "Url",
						"description": "The url on how/where to obtain this food.",
						"type": "string",
						"format": "uri"
					}
				}
			}
		},
		"effect": {
			"$id": "#food/effect",
			"title": "Effect",
			"type": "string",
			"description": "Effect this food has on pets."
		},
		"perk": {
			"$id": "#food/perk",
			"title": "Perk",
			"type": "boolean",
			"description": "Whether the food is a perk or consumable."
		},
		"sprites": {
			"$id": "#food/sprites",
			"title": "Sprites",
			"description": "The food's previous and current sprites.",
			"type": "object",
			"required": [
				"standard"
			],
			"properties": {
				"standard": {
					"$id": "#food/sprites/standard",
					"title": "Standard",
					"description": "The food's current sprite.",
					"type": "string",
					"format": "uri"
				},
				"classic": {
					"$id": "#food/sprites/classic",
					"title": "Classic",
					"description": "The food's previous sprite.",
					"type": "string",
					"format": "uri"
				}
			}
		}
	}
}

=== apacha01/sapi/db/foods.json
[
	{
		"name": "Honey",
		"shop_tier": {
			"shop_tier": 1,
			"url": "https://sapi.com/api/v1/foods?tier=1"
		},
		"sources": [
			{
				"source": "Shop in Turtle Pack.",
				"url": "https://sapi.com/api/v1/packs/turtle"
			},
			{
				"source": "Shop in Puppy Pack.",
				"url": "https://sapi.com/api/v1/packs/puppy"
			},
			{
				"source": "Gained by a level 1 Beetle at the start of battle.",
				"url": "https://sapi.com/api/v1/pets/beetle"
			},
			{
				"source": "Given by Bear upon faint.",
				"url": "https://sapi.com/api/v1/pets/bear"
			},
			{
				"source": "Shop in Weekly Packs.",
				"url": "https://sapi.com/api/v1/packs/weekly"
			},
			{
				"source": "Shop in Custom Packs.",
				"url": "https://sapi.com/api/v1/packs/custom"
			}
		],
		"effect": "Summon one 1/1 Bee after fainting.",
		"perk": true,
		"sprites": {
			"standard": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/foods/standard/Honey.png",
			"classic": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/foods/classic/Honey_Classic.png"
		}
	},
	{
		"name": "Strawberry",
		"shop_tier": {
			"shop_tier": 1,
			"url": "https://sapi.com/api/v1/foods?tier=1"
		},
		"sources": [
			{
				"source": "Shop in Star Pack.",
				"url": "https://sapi.com/api/v1/packs/star"
			},
			{
				"source": "Shop in Custom Packs.",
				"url": "https://sapi.com/api/v1/packs/custom"
			}
		],
		"effect": "Enables Strawberry abilities.",
		"perk": true,
		"sprites": {
			"standard": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/foods/standard/Strawberry.png",
			"classic": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/foods/classic/Strawberry_Classic.png"
		}
	},
	{
		"name": "Blueberry",
		"shop_tier": {
			"shop_tier": 1,
			"url": "https://sapi.com/api/v1/foods?tier=1"
		},
		"sources": [
			{
				"source": "Shop in Weekly Packs.",
				"url": "https://sapi.com/api/v1/packs/weekly"
			},
			{
				"source": "Shop in Custom Packs.",
				"url": "https://sapi.com/api/v1/packs/custom"
			}
		],
		"effect": "Prioritize this for enemy random abilities.",
		"perk": true,
		"sprites": {
			"standard": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/foods/standard/Blueberry.png",
			"classic": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/foods/classic/Blueberry_Classic.png"
		}
	},
	{
		"name": "Egg",
		"shop_tier": {
			"shop_tier": 1,
			"url": "https://sapi.com/api/v1/foods?tier=1"
		},
		"sources": [
			{
				"source": "Shop Golden Pack.",
				"url": "https://sapi.com/api/v1/packs/golden"
			},
			{
				"source": "Nests summoned by a Robin have an innate Egg.",
				"url": "https://sapi.com/api/v1/tokens/nest"
			},
			{
				"source": "Shop in Weekly Packs.",
				"url": "https://sapi.com/api/v1/packs/weekly"
			},
			{
				"source": "Shop in Custom Packs.",
				"url": "https://sapi.com/api/v1/packs/custom"
			}
		],
		"effect": "Deal 2 damage before attacking, once.",
		"perk": true,
		"sprites": {
			"standard": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/foods/standard/Egg.png",
			"classic": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/foods/classic/Egg_Classic.png"
		}
	},
	{
		"name": "Meat_Bone",
		"shop_tier": {
			"shop_tier": 2,
			"url": "https://sapi.com/api/v1/foods?tier=2"
		},
		"sources": [
			{
				"source": "Shop in Turtle Pack.",
				"url": "https://sapi.com/api/v1/packs/turtle"
			},
			{
				"source": "Shop in Puppy Pack.",
				"url": "https://sapi.com/api/v1/packs/puppy"
			},
			{
				"source": "Gained by a level 2 Beetle at the start of battle.",
				"url": "https://sapi.com/api/v1/pets/beetle"
			},
			{
				"source": "Shop in Weekly Packs.",
				"url": "https://sapi.com/api/v1/packs/weekly"
			},
			{
				"source": "Shop in Custom Packs.",
				"url": "https://sapi.com/api/v1/packs/custom"
			}
		],
		"effect": "Attack with +3 damage.",
		"perk": true,
		"sprites": {
			"standard": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/foods/standard/Meat_Bone.png",
			"classic": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/foods/classic/Meat_Bone_Classic.png"
		}
	},
	{
		"name": "Rice",
		"shop_tier": {
			"shop_tier": 2,
			"url": "https://sapi.com/api/v1/foods?tier=2"
		},
		"sources": [
			{
				"source": "Shop in Puppy Pack.",
				"url": "https://sapi.com/api/v1/packs/puppy"
			},
			{
				"source": "Dolphins summoned by a Beluga Sturgeon have innate Rice.",
				"url": "https://sapi.com/api/v1/pets/beluga_sturgeon"
			},
			{
				"source": "Shop in Weekly Packs.",
				"url": "https://sapi.com/api/v1/packs/weekly"
			},
			{
				"source": "Shop in Custom Packs.",
				"url": "https://sapi.com/api/v1/packs/custom"
			}
		],
		"effect": "Sell for +2 gold.",
		"perk": true,
		"sprites": {
			"standard": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/foods/standard/Rice.png",
			"classic": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/foods/classic/Rice_Classic.png"
		}
	},
	{
		"name": "Cherry",
		"shop_tier": {
			"shop_tier": 2,
			"url": "https://sapi.com/api/v1/foods?tier=2"
		},
		"sources": [
			{
				"source": "Shop Golden Pack.",
				"url": "https://sapi.com/api/v1/packs/golden"
			},
			{
				"source": "Shop in Weekly Packs.",
				"url": "https://sapi.com/api/v1/packs/weekly"
			},
			{
				"source": "Shop in Custom Packs.",
				"url": "https://sapi.com/api/v1/packs/custom"
			}
		],
		"effect": "Gain 2 Trumpet on faint.",
		"perk": true,
		"sprites": {
			"standard": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/foods/standard/Cherry.png",
			"classic": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/foods/classic/Cherry_Classic.png"
		}
	},
	{
		"name": "Chocolate_Cake",
		"shop_tier": {
			"shop_tier": 2,
			"url": "https://sapi.com/api/v1/foods?tier=2"
		},
		"sources": [
			{
				"source": "Shop Golden Pack.",
				"url": "https://sapi.com/api/v1/packs/golden"
			},
			{
				"source": "Shop in Weekly Packs.",
				"url": "https://sapi.com/api/v1/packs/weekly"
			},
			{
				"source": "Shop in Custom Packs.",
				"url": "https://sapi.com/api/v1/packs/custom"
			}
		],
		"effect": "Gain +3 experience and faint before attacking.",
		"perk": true,
		"sprites": {
			"standard": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/foods/standard/Chocolate_Cake.png",
			"classic": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/foods/classic/Chocolate_Cake_Classic.png"
		}
	},
	{
		"name": "Garlic",
		"shop_tier": {
			"shop_tier": 3,
			"url": "https://sapi.com/api/v1/foods?tier=3"
		},
		"sources": [
			{
				"source": "Shop in Turtle Pack.",
				"url": "https://sapi.com/api/v1/packs/turtle"
			},
			{
				"source": "Shop in Puppy Pack.",
				"url": "https://sapi.com/api/v1/packs/puppy"
			},
			{
				"source": "Gained by a level 3 Beetle at the start of battle.",
				"url": "https://sapi.com/api/v1/pets/beetle"
			},
			{
				"source": "Given to friends by the Garlic Press Toy (which can be gained from a Lemur on buy).",
				"url": "https://sapi.com/api/v1/toys/garlic_press"
			},
			{
				"source": "Shop in Weekly Packs.",
				"url": "https://sapi.com/api/v1/packs/weekly"
			},
			{
				"source": "Shop in Custom Packs.",
				"url": "https://sapi.com/api/v1/packs/custom"
			}
		],
		"effect": "Take 2 less damage.",
		"perk": true,
		"sprites": {
			"standard": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/foods/standard/Garlic.png",
			"classic": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/foods/classic/Garlic_Classic.png"
		}
	},
	{
		"name": "Croissant",
		"shop_tier": {
			"shop_tier": 3,
			"url": "https://sapi.com/api/v1/foods?tier=3"
		},
		"sources": [
			{
				"source": "Shop in Puppy Pack.",
				"url": "https://sapi.com/api/v1/packs/puppy"
			},
			{
				"source": "Shop in Weekly Packs.",
				"url": "https://sapi.com/api/v1/packs/weekly"
			},
			{
				"source": "Shop in Custom Packs.",
				"url": "https://sapi.com/api/v1/packs/custom"
			}
		],
		"effect": "Gain +1 attack at end of turn.",
		"perk": true,
		"sprites": {
			"standard": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/foods/standard/Croissant.png",
			"classic": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/foods/classic/Croissant_Classic.png"
		}
	},
	{
		"name": "Cucumber",
		"shop_tier": {
			"shop_tier": 3,
			"url": "https://sapi.com/api/v1/foods?tier=3"
		},
		"sources": [
			{
				"source": "Shop in Star Pack.",
				"url": "https://sapi.com/api/v1/packs/star"
			},
			{
				"source": "Shop in Weekly Packs.",
				"url": "https://sapi.com/api/v1/packs/weekly"
			},
			{
				"source": "Shop in Custom Packs.",
				"url": "https://sapi.com/api/v1/packs/custom"
			}
		],
		"effect": "Gain +1 health at end of turn.",
		"perk": true,
		"sprites": {
			"standard": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/foods/standard/Cucumber.png",
			"classic": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/foods/classic/Cucumber_Classic.png"
		}
	},
	{
		"name": "Pineapple",
		"shop_tier": {
			"shop_tier": 3,
			"url": "https://sapi.com/api/v1/foods?tier=3"
		},
		"sources": [
			{
				"source": "Shop in Weekly Packs.",
				"url": "https://sapi.com/api/v1/packs/weekly"
			},
			{
				"source": "Shop in Custom Packs.",
				"url": "https://sapi.com/api/v1/packs/custom"
			}
		],
		"effect": "Ability deals 2 more damage.",
		"perk": true,
		"sprites": {
			"standard": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/foods/standard/Pineapple.png",
			"classic": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/foods/classic/Pineapple_Classic.png"
		}
	},
	{
		"name": "Eggplant",
		"shop_tier": {
			"shop_tier": 3,
