=== apacha01/sapi/src/schemas/packs-schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "https://raw.githubusercontent.com/apacha01/sapi/master/src/schemas/packs-schema.json",
	"title": "SAP Pack object",
	"type": "object",
	"required": [
		"name",
		"pets",
		"foods",
		"description"
	],
	"properties": {
		"name": {
			"$id": "#root/name",
			"title": "Pack name",
			"type": "string"
		},
		"pets": {
			"$id": "#root/pets",
			"title": "Pack pets",
			"description": "Pack pets list for each tier.",
			"type": "object",
			"required": [
				"tier_1_pets",
				"tier_2_pets",
				"tier_3_pets",
				"tier_4_pets",
				"tier_5_pets",
				"tier_6_pets"
			],
			"properties": {
				"tier_1_pets": {
					"$id": "#root/pets/tier_1_pets",
					"title": "Pack tier 1 pets",
					"description": "Pack pets in tier 1.",
					"type": "array",
					"items": {
						"$id": "#root/pets/tier_1_pets/items",
						"title": "Pack tier 1 pet",
						"description": "Pack pet in the list of pets of tier 1.",
						"type": "object",
						"required": [
							"name",
							"url"
						],
						"properties": {
							"name": {
								"$id": "#root/pets/tier_1_pets/items/name",
								"title": "Pack tier 1 pet name",
								"description": "Name of this tier 1 pet in the pack.",
								"type": "string"
							},
							"url": {
								"$id": "#root/pets/tier_1_pets/items/url",
								"title": "Pack tier 1 pet url",
								"description": "Url to find more information about this tier 1 pet in the pack.",
								"type": "string",
								"format": "uri"
							}
						}
					}
				},
				"tier_2_pets": {
					"$id": "#root/pets/tier_2_pets",
					"title": "Pack tier 2 pets",
					"description": "Pack pets in tier 2.",
					"type": "array",
					"items": {
						"$id": "#root/pets/tier_2_pets/items",
						"title": "Pack tier 2 pet",
						"description": "Pack pet in the list of pets of tier 2.",
						"type": "object",
						"required": [
							"name",
							"url"
						],
						"properties": {
							"name": {
								"$id": "#root/pets/tier_2_pets/items/name",
								"title": "Pack tier 2 pet name",
								"description": "Name of this tier 2 pet in the pack.",
								"type": "string"
							},
							"url": {
								"$id": "#root/pets/tier_2_pets/items/url",
								"title": "Pack tier 2 pet url",
								"description": "Url to find more information about this tier 2 pet in the pack.",
								"type": "string",
								"format": "uri"
							}
						}
					}
				},
				"tier_3_pets": {
					"$id": "#root/pets/tier_3_pets",
					"title": "Pack tier 3 pets",
					"description": "Pack pets in tier 3.",
					"type": "array",
					"items": {
						"$id": "#root/pets/tier_3_pets/items",
						"title": "Pack tier 3 pet",
						"description": "Pack pet in the list of pets of tier 3.",
						"type": "object",
						"required": [
							"name",
							"url"
						],
						"properties": {
							"name": {
								"$id": "#root/pets/tier_3_pets/items/name",
								"title": "Pack tier 3 pet name",
								"description": "Name of this tier 3 pet in the pack.",
								"type": "string"
							},
							"url": {
								"$id": "#root/pets/tier_3_pets/items/url",
								"title": "Pack tier 3 pet url",
								"description": "Url to find more information about this tier 3 pet in the pack.",
								"type": "string",
								"format": "uri"
							}
						}
					}
				},
				"tier_4_pets": {
					"$id": "#root/pets/tier_4_pets",
					"title": "Pack tier 4 pets",
					"description": "Pack pets in tier 4.",
					"type": "array",
					"items": {
						"$id": "#root/pets/tier_4_pets/items",
						"title": "Pack tier 4 pet",
						"description": "Pack pet in the list of pets of tier 4.",
						"type": "object",
						"required": [
							"name",
							"url"
						],
						"properties": {
							"name": {
								"$id": "#root/pets/tier_4_pets/items/name",
								"title": "Pack tier 4 pet name",
								"description": "Name of this tier 4 pet in the pack.",
								"type": "string"
							},
							"url": {
								"$id": "#root/pets/tier_4_pets/items/url",
								"title": "Pack tier 4 pet url",
								"description": "Url to find more information about this tier 4 pet in the pack.",
								"type": "string",
								"format": "uri"
							}
						}
					}
				},
				"tier_5_pets": {
					"$id": "#root/pets/tier_5_pets",
					"title": "Pack tier 5 pets",
					"description": "Pack pets in tier 5.",
					"type": "array",
					"items": {
						"$id": "#root/pets/tier_5_pets/items",
						"title": "Pack tier 5 pet",
						"description": "Pack pet in the list of pets of tier 5.",
						"type": "object",
						"required": [
							"name",
							"url"
						],
						"properties": {
							"name": {
								"$id": "#root/pets/tier_5_pets/items/name",
								"title": "Pack tier 5 pet name",
								"description": "Name of this tier 5 pet in the pack.",
								"type": "string"
							},
							"url": {
								"$id": "#root/pets/tier_5_pets/items/url",
								"title": "Pack tier 5 pet url",
								"description": "Url to find more information about this tier 5 pet in the pack.",
								"type": "string",
								"format": "uri"
							}
						}
					}
				},
				"tier_6_pets": {
					"$id": "#root/pets/tier_6_pets",
					"title": "Pack tier 6 pets",
					"description": "Pack pets in tier 6.",
					"type": "array",
					"items": {
						"$id": "#root/pets/tier_6_pets/items",
						"title": "Pack tier 6 pet",
						"description": "Pack pet in the list of pets of tier 6.",
						"type": "object",
						"required": [
							"name",
							"url"
						],
						"properties": {
							"name": {
								"$id": "#root/pets/tier_6_pets/items/name",
								"title": "Pack tier 6 pet name",
								"description": "Name of this tier 6 pet in the pack.",
								"type": "string"
							},
							"url": {
								"$id": "#root/pets/tier_6_pets/items/url",
								"title": "Pack tier 6 pet url",
								"description": "Url to find more information about this tier 6 pet in the pack.",
								"type": "string",
								"format": "uri"
							}
						}
					}
				}
			}
		},
		"foods": {
			"$id": "#root/foods",
			"title": "Pack foods",
			"description": "Pack foods list for each tier.",
			"type": "object",
			"required": [
				"tier_1_foods",
				"tier_2_foods",
				"tier_3_foods",
				"tier_4_foods",
				"tier_5_foods",
				"tier_6_foods"
			],
			"properties": {
				"tier_1_foods": {
					"$id": "#root/foods/tier_1_foods",
					"title": "Pack tier 1 foods",
					"description": "Pack foods list in tier 1.",
					"type": "array",
					"items": {
						"$id": "#root/foods/tier_1_foods/items",
						"title": "Pack tier 1 food",
						"description": "Pack food in the list of foods of tier 1.",
						"type": "object",
						"required": [
							"name",
							"url"
						],
						"properties": {
							"name": {
								"$id": "#root/foods/tier_1_foods/items/name",
								"title": "Pack tier 1 food name",
								"description": "Name of this tier 1 food in the pack.",
								"type": "string"
							},
							"url": {
								"$id": "#root/foods/tier_1_foods/items/url",
								"title": "Pack tier 1 food url",
								"description": "Url to find more information about this tier 1 food in this pack.",
								"type": "string",
								"format": "uri"
							}
						}
					}
				},
				"tier_2_foods": {
					"$id": "#root/foods/tier_2_foods",
					"title": "Pack tier 2 foods",
					"description": "Pack foods list in tier 2.",
					"type": "array",
					"items": {
						"$id": "#root/foods/tier_2_foods/items",
						"title": "Pack tier 2 food",
						"description": "Pack food in the list of foods of tier 2.",
						"type": "object",
						"required": [
							"name",
							"url"
						],
						"properties": {
							"name": {
								"$id": "#root/foods/tier_2_foods/items/name",
								"title": "Pack tier 2 food name",
								"description": "Name of this tier 2 food in the pack.",
								"type": "string"
							},
							"url": {
								"$id": "#root/foods/tier_2_foods/items/url",
								"title": "Pack tier 2 food url",
								"description": "Url to find more information about this tier 2 food in this pack.",
								"type": "string",
								"format": "uri"
							}
						}
					}
				},
				"tier_3_foods": {
					"$id": "#root/foods/tier_3_foods",
					"title": "Pack tier 3 foods",
					"description": "Pack foods list in tier 3.",
					"type": "array",
					"items": {
						"$id": "#root/foods/tier_3_foods/items",
						"title": "Pack tier 3 food",
						"description": "Pack food in the list of foods of tier 3.",
						"type": "object",
						"required": [
							"name",
							"url"
						],
						"properties": {
							"name": {
								"$id": "#root/foods/tier_3_foods/items/name",
								"title": "Pack tier 3 food name",
								"description": "Name of this tier 3 food in the pack.",
								"type": "string"
							},
							"url": {
								"$id": "#root/foods/tier_3_foods/items/url",
								"title": "Pack tier 3 food url",
								"description": "Url to find more information about this tier 3 food in this pack.",
								"type": "string",
								"format": "uri"
							}
						}
					}
				},
				"tier_4_foods": {
					"$id": "#root/foods/tier_4_foods",
					"title": "Pack tier 4 foods",
					"description": "Pack foods list in tier 4.",
					"type": "array",
					"items": {
						"$id": "#root/foods/tier_4_foods/items",
						"title": "Pack tier 4 food",
						"description": "Pack food in the list of foods of tier 4.",
						"type": "object",
						"required": [
							"name",
							"url"
						],
						"properties": {
							"name": {
								"$id": "#root/foods/tier_4_foods/items/name",
								"title": "Pack tier 4 food name",
								"description": "Name of this tier 4 food in the pack.",
								"type": "string"
							},
							"url": {
								"$id": "#root/foods/tier_4_foods/items/url",
								"title": "Pack tier 4 food url",
								"description": "Url to find more information about this tier 4 food in this pack.",
								"type": "string",
								"format": "uri"
							}
						}
					}
				},
				"tier_5_foods": {
					"$id": "#root/foods/tier_5_foods",
					"title": "Pack tier 5 foods",
					"description": "Pack foods list in tier 5.",
					"type": "array",
					"items": {
						"$id": "#root/foods/tier_5_foods/items",
						"title": "Pack tier 5 food",
						"description": "Pack food in the list of foods of tier 5.",
						"type": "object",
						"required": [
							"name",
							"url"
						],
						"properties": {
							"name": {
								"$id": "#root/foods/tier_5_foods/items/name",
								"title": "Pack tier 5 food name",
								"description": "Name of this tier 5 food in the pack.",
								"type": "string"
							},
							"url": {
								"$id": "#root/foods/tier_5_foods/items/url",
								"title": "Pack tier 5 food url",
								"description": "Url to find more information about this tier 5 food in this pack.",
								"type": "string",
								"format": "uri"
							}
						}
					}
				},
				"tier_6_foods": {
					"$id": "#root/foods/tier_6_foods",
					"title": "Pack tier 6 foods",
					"description": "Pack foods list in tier 6.",
					"type": "array",
					"items": {
						"$id": "#root/foods/tier_6_foods/items",
						"title": "Pack tier 6 food",
						"description": "Pack food in the list of foods of tier 6.",
						"type": "object",
						"required": [
							"name",
							"url"
						],
						"properties": {
							"name": {
								"$id": "#root/foods/tier_6_foods/items/name",
								"title": "Pack tier 6 food name",
								"description": "Name of this tier 6 food in the pack.",
								"type": "string"
							},
							"url": {
								"$id": "#root/foods/tier_6_foods/items/url",
								"title": "Pack tier 6 food url",
								"description": "Url to find more information about this tier 6 food in this pack.",
								"type": "string",
								"format": "uri"
							}
						}
					}
				}
			}
		},
		"description": {
			"$id": "#root/description",
			"title": "Pack description",
			"description": "Description of when this pack was released or how this pack works in special cases (like Custom or Weekly packs).",
			"type": "string"
		}
	}
}

=== apacha01/sapi/db/packs.json
[
	{
		"name": "Turtle",
		"pets": {
			"tier_1_pets": [
				{
					"name": "Duck",
					"url": "https://sapi.com/pets/duck"
				},
				{
					"name": "Beaver",
					"url": "https://sapi.com/pets/beaver"
				},
				{
					"name": "Otter",
					"url": "https://sapi.com/pets/otter"
				},
				{
					"name": "Pig",
					"url": "https://sapi.com/pets/pig"
				},
				{
					"name": "Ant",
					"url": "https://sapi.com/pets/ant"
				},
				{
					"name": "Mosquito",
					"url": "https://sapi.com/pets/mosquito"
				},
				{
					"name": "Mouse",
					"url": "https://sapi.com/pets/mouse"
				},
				{
					"name": "Fish",
					"url": "https://sapi.com/pets/fish"
				},
				{
					"name": "Cricket",
					"url": "https://sapi.com/pets/cricket"
				},
				{
					"name": "Horse",
					"url": "https://sapi.com/pets/horse"
				}
			],
			"tier_2_pets": [
				{
					"name": "Snail",
					"url": "https://sapi.com/pets/snail"
				},
				{
					"name": "Crab",
					"url": "https://sapi.com/pets/crab"
				},
				{
					"name": "Swan",
					"url": "https://sapi.com/pets/swan"
				},
				{
					"name": "Rat",
					"url": "https://sapi.com/pets/rat"
				},
				{
					"name": "Hedgehog",
					"url": "https://sapi.com/pets/hedgehog"
				},
				{
					"name": "Peacock",
					"url": "https://sapi.com/pets/peacock"
				},
				{
					"name": "Flamingo",
					"url": "https://sapi.com/pets/flamingo"
				},
				{
					"name": "Worm",
					"url": "https://sapi.com/pets/worm"
				},
				{
					"name": "Kangaroo",
					"url": "https://sapi.com/pets/kangaroo"
				},
				{
					"name": "Spider",
					"url": "https://sapi.com/pets/spider"
				}
			],
			"tier_3_pets": [
				{
					"name": "Dodo",
					"url": "https://sapi.com/pets/dodo"
				},
				{
					"name": "Badger",
					"url": "https://sapi.com/pets/badger"
				},
				{
					"name": "Dolphin",
					"url": "https://sapi.com/pets/dolphin"
				},
				{
					"name": "Giraffe",
					"url": "https://sapi.com/pets/giraffe"
				},
				{
					"name": "Elephant",
					"url": "https://sapi.com/pets/elephant"
				},
				{
					"name": "Camel",
					"url": "https://sapi.com/pets/camel"
				},
				{
					"name": "Rabbit",
					"url": "https://sapi.com/pets/rabbit"
				},
				{
					"name": "Ox",
					"url": "https://sapi.com/pets/ox"
				},
				{
					"name": "Dog",
					"url": "https://sapi.com/pets/dog"
				},
				{
					"name": "Sheep",
					"url": "https://sapi.com/pets/sheep"
				}
			],
			"tier_4_pets": [
				{
					"name": "Skunk",
					"url": "https://sapi.com/pets/skunk"
				},
				{
					"name": "Hippo",
					"url": "https://sapi.com/pets/hippo"
				},
				{
					"name": "Bison",
					"url": "https://sapi.com/pets/bison"
				},
				{
					"name": "Blowfish",
					"url": "https://sapi.com/pets/blowfish"
				},
				{
					"name": "Turtle",
					"url": "https://sapi.com/pets/turtle"
				},
				{
					"name": "Squirrel",
					"url": "https://sapi.com/pets/squirrel"
				},
				{
					"name": "Penguin",
					"url": "https://sapi.com/pets/penguin"
				},
				{
					"name": "Deer",
					"url": "https://sapi.com/pets/deer"
				},
				{
					"name": "Whale",
					"url": "https://sapi.com/pets/whale"
				},
				{
					"name": "Parrot",
					"url": "https://sapi.com/pets/parrot"
				}
			],
			"tier_5_pets": [
				{
					"name": "Scorpion",
					"url": "https://sapi.com/pets/scorpion"
				},
				{
					"name": "Crocodile",
					"url": "https://sapi.com/pets/crocodile"
				},
				{
					"name": "Rhino",
					"url": "https://sapi.com/pets/rhino"
				},
				{
					"name": "Monkey",
					"url": "https://sapi.com/pets/monkey"
				},
				{
					"name": "Armadillo",
					"url": "https://sapi.com/pets/armadillo"
				},
				{
					"name": "Cow",
					"url": "https://sapi.com/pets/cow"
				},
				{
					"name": "Seal",
					"url": "https://sapi.com/pets/seal"
				},
				{
					"name": "Rooster",
					"url": "https://sapi.com/pets/rooster"
				},
				{
					"name": "Shark",
					"url": "https://sapi.com/pets/shark"
				},
				{
					"name": "Turkey",
					"url": "https://sapi.com/pets/turkey"
				}
			],
			"tier_6_pets": [
				{
					"name": "Leopard",
					"url": "https://sapi.com/pets/leopard"
				},
				{
					"name": "Boar",
					"url": "https://sapi.com/pets/boar"
				},
				{
					"name": "Tiger",
					"url": "https://sapi.com/pets/tiger"
				},
				{
					"name": "Wolverine",
					"url": "https://sapi.com/pets/wolverine"
				},
				{
					"name": "Gorilla",
					"url": "https://sapi.com/pets/gorilla"
				},
				{
					"name": "Dragon",
					"url": "https://sapi.com/pets/dragon"
				},
				{
					"name": "Mammoth",
					"url": "https://sapi.com/pets/mammoth"
				},
				{
					"name": "Cat",
					"url": "https://sapi.com/pets/cat"
				},
				{
					"name": "Snake",
					"url": "https://sapi.com/pets/snake"
				},
				{
					"name": "Fly",
					"url": "https://sapi.com/pets/fly"
				}
			]
		},
		"foods": {
			"tier_1_foods": [
				{
					"name": "Honey",
					"url": "https://sapi.com/foods/honey"
				},
				{
					"name": "Apple",
					"url": "https://sapi.com/foods/apple"
				}
			],
			"tier_2_foods": [
				{
					"name": "Cupcake",
					"url": "https://sapi.com/foods/cupcake"
				},
				{
					"name": "Meat_Bone",
					"url": "https://sapi.com/foods/meat_bone"
				},
				{
					"name": "Sleeping_Pill",
					"url": "https://sapi.com/foods/sleeping_pill"
				}
			],
			"tier_3_foods": [
				{
					"name": "Garlic",
					"url": "https://sapi.com/foods/garlic"
				},
				{
					"name": "Salad_Bowl",
					"url": "https://sapi.com/foods/salad_bowl"
				}
			],
			"tier_4_foods": [
				{
					"name": "Pear",
					"url": "https://sapi.com/foods/pear"
				},
				{
					"name": "Canned_Food",
					"url": "https://sapi.com/foods/canned_food"
				}
			],
			"tier_5_foods": [
				{
					"name": "Sushi",
					"url": "https://sapi.com/foods/sushi"
				},
				{
					"name": "Chocolate",
					"url": "https://sapi.com/foods/chocolate"
				},
				{
					"name": "Chili",
					"url": "https://sapi.com/foods/chili"
				}
			],
			"tier_6_foods": [
				{
					"name": "Pizza",
					"url": "https://sapi.com/foods/pizza"
				},
				{
					"name": "Steak",
					"url": "https://sapi.com/foods/steak"
				},
				{
					"name": "Mushroom",
					"url": "https://sapi.com/foods/mushroom"
				},
				{
					"name": "Melon",
					"url": "https://sapi.com/foods/melon"
				}
			]
		},
		"description": "The Turtle Pack is the first pack in Super Auto Pets and is immediately available to all players for free."
	},
	{
		"name": "Golden",
		"pets": {
			"tier_1_pets": [
				{
					"name": "Chipmunk",
					"url": "https://sapi.com/pets/chipmunk"
				},
				{
					"name": "Bulldog",
					"url": "https://sapi.com/pets/bulldog"
				},
				{
					"name": "Groundhog",
					"url": "https://sapi.com/pets/groundhog"
				},
				{
					"name": "Cone_Snail",
					"url": "https://sapi.com/pets/cone_snail"
				},
				{
					"name": "Goose",
					"url": "https://sapi.com/pets/goose"
				},
				{
					"name": "Pied_Tamarin",
					"url": "https://sapi.com/pets/pied_tamarin"
				},
				{
					"name": "Opossum",
					"url": "https://sapi.com/pets/opossum"
				},
				{
					"name": "Silkmoth",
					"url": "https://sapi.com/pets/silkmoth"
				},
				{
					"name": "Magpie",
					"url": "https://sapi.com/pets/magpie"
				}
			],
			"tier_2_pets": [
				{
					"name": "Hercules_Beetle",
					"url": "https://sapi.com/pets/hercules_beetle"
				},
				{
					"name": "Stoat",
					"url": "https://sapi.com/pets/stoat"
				},
				{
					"name": "Black_Necked_Stilt",
					"url": "https://sapi.com/pets/black_necked_stilt"
				},
				{
					"name": "Squid",
					"url": "https://sapi.com/pets/squid"
				},
				{
					"name": "Sea_Urchin",
					"url": "https://sapi.com/pets/sea_urchin"
				},
				{
					"name": "Door_Head_Ant",
					"url": "https://sapi.com/pets/door_head_ant"
				},
				{
					"name": "Lizard",
					"url": "https://sapi.com/pets/lizard"
				},
				{
					"name": "Sea_Turtle",
					"url": "https://sapi.com/pets/sea_turtle"
				},
				{
					"name": "Gazelle",
					"url": "https://sapi.com/pets/gazelle"
				},
				{
					"name": "African_Penguin",
					"url": "https://sapi.com/pets/african_penguin"
				}
			],
			"tier_3_pets": [
				{
					"name": "Musk_Ox",
					"url": "https://sapi.com/pets/musk_ox"
				},
				{
					"name": "Flea",
					"url": "https://sapi.com/pets/flea"
				},
				{
					"name": "Royal_Flycatcher",
					"url": "https://sapi.com/pets/royal_flycatcher"
				},
				{
					"name": "Surgeon_Fish",
					"url": "https://sapi.com/pets/surgeon_fish"
				},
				{
					"name": "Weasel",
					"url": "https://sapi.com/pets/weasel"
				},
				{
					"name": "Guineafowl",
					"url": "https://sapi.com/pets/guineafowl"
				},
				{
					"name": "Betta_Fish",
					"url": "https://sapi.com/pets/betta_fish"
				},
				{
					"name": "Meerkat",
					"url": "https://sapi.com/pets/meerkat"
				},
				{
					"name": "Flying_Fish",
					"url": "https://sapi.com/pets/flying_fish"
				},
				{
					"name": "Baboon",
					"url": "https://sapi.com/pets/baboon"
				},
				{
					"name": "Osprey",
					"url": "https://sapi.com/pets/osprey"
				}
			],
			"tier_4_pets": [
				{
					"name": "Manatee",
					"url": "https://sapi.com/pets/manatee"
				},
				{
					"name": "Cuttlefish",
					"url": "https://sapi.com/pets/cuttlefish"
				},
				{
					"name": "Egyptian_Vulture",
					"url": "https://sapi.com/pets/egyptian_vulture"
				},
				{
					"name": "Saiga_Antelope",
					"url": "https://sapi.com/pets/saiga_antelope"
				},
				{
					"name": "Sealion",
					"url": "https://sapi.com/pets/sealion"
				},
				{
					"name": "Vaquita",
					"url": "https://sapi.com/pets/vaquita"
				},
				{
					"name": "Slug",
					"url": "https://sapi.com/pets/slug"
				},
				{
					"name": "Poison_Dart_Frog",
					"url": "https://sapi.com/pets/poison_dart_frog"
				},
				{
					"name": "Secretary_Bird",
					"url": "https://sapi.com/pets/secretary_bird"
				},
				{
