=== apacha01/sapi/src/schemas/tokens-schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "https://raw.githubusercontent.com/apacha01/sapi/master/src/schemas/tokens-schema.json",
	"title": "Token",
	"description": "SAP Token object.",
	"type": "object",
	"required": [
		"name",
		"tier_info",
		"sprites",
		"abilities",
		"summoned_from",
		"stats"
	],
	"properties": {
		"name": {
			"$id": "#root/name",
			"title": "Token name",
			"type": "string"
		},
		"tier_info": {
			"$id": "#root/tier_info",
			"title": "Tier_info",
			"description": "Token tier and url.",
			"type": "object",
			"required": [
				"tier",
				"url"
			],
			"properties": {
				"tier": {
					"$id": "#root/tier_info/tier",
					"title": "Token tier number.",
					"type": "integer",
					"minimum": 1,
					"maximum": 6
				},
				"url": {
					"$id": "#root/tier_info/url",
					"title": "Token tier url",
					"type": "string",
					"format": "uri"
				}
			}
		},
		"sprites": {
			"$id": "#root/sprites",
			"title": "Token sprites",
			"description": "Token current and previous sprites.",
			"type": "object",
			"required": [
				"standard"
			],
			"properties": {
				"standard": {
					"$id": "#root/sprites/standard",
					"title": "Token standard sprite",
					"description": "Token current sprite.",
					"type": "string",
					"format": "uri"
				},
				"classic": {
					"$id": "#root/sprites/classic",
					"title": "Token classic sprite",
					"description": "Token previous sprite.",
					"type": "string",
					"format": "uri",
					"default": null
				}
			}
		},
		"abilities": {
			"$id": "#root/abilities",
			"title": "Token abilities",
			"description": "Token abilities for each level.",
			"type": "object",
			"required": [
				"lv1_ability",
				"lv2_ability",
				"lv3_ability"
			],
			"properties": {
				"lv1_ability": {
					"$id": "#root/abilities/lv1_ability",
					"title": "Token level 1 ability",
					"description": "Token level 1 ability description.",
					"type": "string"
				},
				"lv2_ability": {
					"$id": "#root/abilities/lv2_ability",
					"title": "Token level 2 ability",
					"description": "Token level 2 ability description.",
					"type": "string"
				},
				"lv3_ability": {
					"$id": "#root/abilities/lv3_ability",
					"title": "Token level 3 ability",
					"description": "Token level 3 ability description.",
					"type": "string"
				}
			}
		},
		"summoned_from": {
			"$id": "#root/summoned_from",
			"title": "Token summoning information",
			"description": "The source of this token, i.e., how to summon it.",
			"type": "object",
			"required": [
				"source",
				"url"
			],
			"properties": {
				"source": {
					"$id": "#root/summoned_from/source",
					"title": "Token source",
					"description": "Description on how/where the token is obtained.",
					"type": "string"
				},
				"url": {
					"$id": "#root/summoned_from/url",
					"title": "Token source url",
					"description": "Uri to find more information on the source of this token.",
					"type": "string",
					"format": "uri"
				}
			}
		},
		"stats": {
			"$id": "#root/stats",
			"title": "Token stats",
			"description": "Token stats for each level.",
			"type": "object",
			"required": [
				"lv1_stats",
				"lv2_stats",
				"lv3_stats"
			],
			"properties": {
				"lv1_stats": {
					"$id": "#root/stats/lv1_stats",
					"title": "Token level 1 stats",
					"description": "The stats the token has on level 1 except for experience which is always zero.",
					"type": "array",
					"items": {
						"$id": "#root/stats/lv1_stats/items",
						"title": "Token stat on level 1",
						"description": "A stat the token has on level 1.",
						"type": "object",
						"required": [
							"name",
							"base_stat",
							"url"
						],
						"properties": {
							"name": {
								"$id": "#root/stats/lv1_stats/items/name",
								"title": "Token stat name",
								"description": "The name of a stat the token has.",
								"type": "string"
							},
							"base_stat": {
								"$id": "#root/stats/lv1_stats/items/base_stat",
								"title": "Token stat base number",
								"description": "The initial value of a stat the token has.",
								"type": "integer",
								"minimum": 0,
								"maximum": 50
							},
							"url": {
								"$id": "#root/stats/lv1_stats/items/url",
								"title": "Pet stat url",
								"description": "The url of a stat the token has to refer to for more information.",
								"type": "string",
								"format": "uri"
							}
						}
					}
				},
				"lv2_stats": {
					"$id": "#root/stats/lv2_stats",
					"title": "Token level 2 stats",
					"description": "The stats the token has on level 2 except for experience which is always zero.",
					"type": "array",
					"items": {
						"$id": "#root/stats/lv2_stats/items",
						"title": "Token stat on level 2",
						"description": "A stat the token has on level 2.",
						"type": "object",
						"required": [
							"name",
							"base_stat",
							"url"
						],
						"properties": {
							"name": {
								"$id": "#root/stats/lv2_stats/items/name",
								"title": "Token stat name",
								"description": "The name of a stat the token has.",
								"type": "string"
							},
							"base_stat": {
								"$id": "#root/stats/lv2_stats/items/base_stat",
								"title": "Token stat base number",
								"description": "The initial value of a stat the token has.",
								"type": "integer",
								"minimum": 0,
								"maximum": 50
							},
							"url": {
								"$id": "#root/stats/lv2_stats/items/url",
								"title": "Pet stat url",
								"description": "The url of a stat the token has to refer to for more information.",
								"type": "string",
								"format": "uri"
							}
						}
					}
				},
				"lv3_stats": {
					"$id": "#root/stats/lv3_stats",
					"title": "Token level 3 stats",
					"description": "The stats the token has on level 3 except for experience which is always zero.",
					"type": "array",
					"items": {
						"$id": "#root/stats/lv3_stats/items",
						"title": "Token stat on level 3",
						"description": "A stat the token has on level 3.",
						"type": "object",
						"required": [
							"name",
							"base_stat",
							"url"
						],
						"properties": {
							"name": {
								"$id": "#root/stats/lv3_stats/items/name",
								"title": "Token stat name",
								"description": "The name of a stat the token has.",
								"type": "string"
							},
							"base_stat": {
								"$id": "#root/stats/lv3_stats/items/base_stat",
								"title": "Token stat base number",
								"description": "The initial value of a stat the token has.",
								"type": "integer",
								"minimum": 0,
								"maximum": 50
							},
							"url": {
								"$id": "#root/stats/lv3_stats/items/url",
								"title": "Pet stat url",
								"description": "The url of a stat the token has to refer to for more information.",
								"type": "string",
								"format": "uri"
							}
						}
					}
				}
			}
		},
		"notes": {
			"$id": "#root/notes",
			"title": "Token additional notes",
			"description": "Some notes on what the abilities/stats ok this token actually mean.",
			"type": "string",
			"default": null
		}
	}
}

=== apacha01/sapi/db/tokens.json
[
	{
		"name": "Bee",
		"tier_info": {
			"tier": 1,
			"url": "https://sapi.com/api/v1/tokens?tier=1"
		},
		"sprites": {
			"standard": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/tokens/standard/Bee.png",
			"classic": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/tokens/classic/Bee_Classic.png"
		},
		"abilities": {
			"lv1_ability": "",
			"lv2_ability": "",
			"lv3_ability": ""
		},
		"summoned_from": {
			"source": "Any Pet with Honey Perk once it faints.",
			"url": "https://sapi.com/api/v1/foods/honey"
		},
		"stats": {
			"lv1_stats": [
				{
					"name": "hp",
					"base_stat": 1,
					"url": "https://sapi.com/api/v1/stats/hp"
				},
				{
					"name": "attack",
					"base_stat": 1,
					"url": "https://sapi.com/api/v1/stats/atk"
				}
			],
			"lv2_stats": [
				{
					"name": "hp",
					"base_stat": 1,
					"url": "https://sapi.com/api/v1/stats/hp"
				},
				{
					"name": "attack",
					"base_stat": 1,
					"url": "https://sapi.com/api/v1/stats/atk"
				}
			],
			"lv3_stats": [
				{
					"name": "hp",
					"base_stat": 1,
					"url": "https://sapi.com/api/v1/stats/hp"
				},
				{
					"name": "attack",
					"base_stat": 1,
					"url": "https://sapi.com/api/v1/stats/atk"
				}
			]
		},
		"notes": ""
	},
	{
		"name": "Chick",
		"tier_info": {
			"tier": 1,
			"url": "https://sapi.com/api/v1/tokens?tier=1"
		},
		"sprites": {
			"standard": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/tokens/standard/Chick.png",
			"classic": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/tokens/classic/Chick_Classic.png"
		},
		"abilities": {
			"lv1_ability": "",
			"lv2_ability": "",
			"lv3_ability": ""
		},
		"summoned_from": {
			"source": "A Rooster once it faints.",
			"url": "https://sapi.com/api/v1/pets/rooster"
		},
		"stats": {
			"lv1_stats": [
				{
					"name": "hp",
					"base_stat": 1,
					"url": "https://sapi.com/api/v1/stats/hp"
				},
				{
					"name": "attack",
					"base_stat": 0,
					"url": "https://sapi.com/api/v1/stats/atk"
				}
			],
			"lv2_stats": [
				{
					"name": "hp",
					"base_stat": 1,
					"url": "https://sapi.com/api/v1/stats/hp"
				},
				{
					"name": "attack",
					"base_stat": 0,
					"url": "https://sapi.com/api/v1/stats/atk"
				}
			],
			"lv3_stats": [
				{
					"name": "hp",
					"base_stat": 1,
					"url": "https://sapi.com/api/v1/stats/hp"
				},
				{
					"name": "attack",
					"base_stat": 0,
					"url": "https://sapi.com/api/v1/stats/atk"
				}
			]
		},
		"notes": "Stats on 0 are replaceable for half of the Rooster's attack."
	},
	{
		"name": "Loyal_Chinchilla",
		"tier_info": {
			"tier": 1,
			"url": "https://sapi.com/api/v1/tokens?tier=1"
		},
		"sprites": {
			"standard": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/tokens/standard/Loyal_Chinchilla.png",
			"classic": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/tokens/classic/Loyal_Chinchilla_Classic.png"
		},
		"abilities": {
			"lv1_ability": "",
			"lv2_ability": "",
			"lv3_ability": ""
		},
		"summoned_from": {
			"source": "A Chinchilla upon being sold.",
			"url": "https://sapi.com/api/v1/pets/chinchilla"
		},
		"stats": {
			"lv1_stats": [
				{
					"name": "hp",
					"base_stat": 2,
					"url": "https://sapi.com/api/v1/stats/hp"
				},
				{
					"name": "attack",
					"base_stat": 2,
					"url": "https://sapi.com/api/v1/stats/atk"
				}
			],
			"lv2_stats": [
				{
					"name": "hp",
					"base_stat": 4,
					"url": "https://sapi.com/api/v1/stats/hp"
				},
				{
					"name": "attack",
					"base_stat": 4,
					"url": "https://sapi.com/api/v1/stats/atk"
				}
			],
			"lv3_stats": [
				{
					"name": "hp",
					"base_stat": 6,
					"url": "https://sapi.com/api/v1/stats/hp"
				},
				{
					"name": "attack",
					"base_stat": 6,
					"url": "https://sapi.com/api/v1/stats/atk"
				}
			]
		},
		"notes": ""
	},
	{
		"name": "Zombie_Cricket",
		"tier_info": {
			"tier": 1,
			"url": "https://sapi.com/api/v1/tokens?tier=1"
		},
		"sprites": {
			"standard": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/tokens/standard/Zombie_Cricket.png",
			"classic": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/tokens/classic/Zombie_Cricket_Classic.png"
		},
		"abilities": {
			"lv1_ability": "",
			"lv2_ability": "",
			"lv3_ability": ""
		},
		"summoned_from": {
			"source": "A Cricket once it faints.",
			"url": "https://sapi.com/api/v1/pets/cricket"
		},
		"stats": {
			"lv1_stats": [
				{
					"name": "hp",
					"base_stat": 1,
					"url": "https://sapi.com/api/v1/stats/hp"
				},
				{
					"name": "attack",
					"base_stat": 1,
					"url": "https://sapi.com/api/v1/stats/atk"
				}
			],
			"lv2_stats": [
				{
					"name": "hp",
					"base_stat": 2,
					"url": "https://sapi.com/api/v1/stats/hp"
				},
				{
					"name": "attack",
					"base_stat": 2,
					"url": "https://sapi.com/api/v1/stats/atk"
				}
			],
			"lv3_stats": [
				{
					"name": "hp",
					"base_stat": 3,
					"url": "https://sapi.com/api/v1/stats/hp"
				},
				{
					"name": "attack",
					"base_stat": 3,
					"url": "https://sapi.com/api/v1/stats/atk"
				}
			]
		},
		"notes": ""
	},
	{
		"name": "Dirty_Rat",
		"tier_info": {
			"tier": 1,
			"url": "https://sapi.com/api/v1/tokens?tier=1"
		},
		"sprites": {
			"standard": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/tokens/standard/Dirty_Rat.png",
			"classic": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/tokens/classic/Dirty_Rat_Classic.png"
		},
		"abilities": {
			"lv1_ability": "",
			"lv2_ability": "",
			"lv3_ability": ""
		},
		"summoned_from": {
			"source": "A Rat once it faints.",
			"url": "https://sapi.com/api/v1/pets/rat"
		},
		"stats": {
			"lv1_stats": [
				{
					"name": "hp",
					"base_stat": 1,
					"url": "https://sapi.com/api/v1/stats/hp"
				},
				{
					"name": "attack",
					"base_stat": 1,
					"url": "https://sapi.com/api/v1/stats/atk"
				}
			],
			"lv2_stats": [
				{
					"name": "hp",
					"base_stat": 1,
					"url": "https://sapi.com/api/v1/stats/hp"
				},
				{
					"name": "attack",
					"base_stat": 1,
					"url": "https://sapi.com/api/v1/stats/atk"
				}
			],
			"lv3_stats": [
				{
					"name": "hp",
					"base_stat": 1,
					"url": "https://sapi.com/api/v1/stats/hp"
				},
				{
					"name": "attack",
					"base_stat": 1,
					"url": "https://sapi.com/api/v1/stats/atk"
				}
			]
		},
		"notes": ""
	},
	{
		"name": "Lizard_Tail",
		"tier_info": {
			"tier": 1,
			"url": "https://sapi.com/api/v1/tokens?tier=1"
		},
		"sprites": {
			"standard": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/tokens/standard/Lizard_Tail.png",
			"classic": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/tokens/standard/Lizard_Tail.png"
		},
		"abilities": {
			"lv1_ability": "",
			"lv2_ability": "",
			"lv3_ability": ""
		},
		"summoned_from": {
			"source": "A Lizard when it is Hurt.",
			"url": "https://sapi.com/api/v1/pets/lizard"
		},
		"stats": {
			"lv1_stats": [
				{
					"name": "hp",
					"base_stat": 1,
					"url": "https://sapi.com/api/v1/stats/hp"
				},
				{
					"name": "attack",
					"base_stat": 3,
					"url": "https://sapi.com/api/v1/stats/atk"
				}
			],
			"lv2_stats": [
				{
					"name": "hp",
					"base_stat": 2,
					"url": "https://sapi.com/api/v1/stats/hp"
				},
				{
					"name": "attack",
					"base_stat": 6,
					"url": "https://sapi.com/api/v1/stats/atk"
				}
			],
			"lv3_stats": [
				{
					"name": "hp",
					"base_stat": 3,
					"url": "https://sapi.com/api/v1/stats/hp"
				},
				{
					"name": "attack",
					"base_stat": 9,
					"url": "https://sapi.com/api/v1/stats/atk"
				}
			]
		},
		"notes": "https://sapi.com/api/v1/pets/lizard"
	},
	{
		"name": "Nest",
		"tier_info": {
			"tier": 1,
			"url": "https://sapi.com/api/v1/tokens?tier=1"
		},
		"sprites": {
			"standard": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/tokens/standard/Nest.png",
			"classic": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/tokens/standard/Nest.png"
		},
		"abilities": {
			"lv1_ability": "",
			"lv2_ability": "",
			"lv3_ability": ""
		},
		"summoned_from": {
			"source": "A Robin at the start of battle.",
			"url": "https://sapi.com/api/v1/pets/robin"
		},
		"stats": {
			"lv1_stats": [
				{
					"name": "hp",
					"base_stat": 3,
					"url": "https://sapi.com/api/v1/stats/hp"
				},
				{
					"name": "attack",
					"base_stat": 2,
					"url": "https://sapi.com/api/v1/stats/atk"
				}
			],
			"lv2_stats": [
				{
					"name": "hp",
					"base_stat": 6,
					"url": "https://sapi.com/api/v1/stats/hp"
				},
				{
					"name": "attack",
					"base_stat": 4,
					"url": "https://sapi.com/api/v1/stats/atk"
				}
			],
			"lv3_stats": [
				{
					"name": "hp",
					"base_stat": 9,
					"url": "https://sapi.com/api/v1/stats/hp"
				},
				{
					"name": "attack",
					"base_stat": 6,
					"url": "https://sapi.com/api/v1/stats/atk"
				}
			]
		},
		"notes": ""
	},
	{
		"name": "Ram",
		"tier_info": {
			"tier": 1,
			"url": "https://sapi.com/api/v1/tokens?tier=1"
		},
		"sprites": {
			"standard": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/tokens/standard/Ram.png",
			"classic": "https://raw.githubusercontent.com/apacha01/assets/sap/super-auto-pets/tokens/classic/Ram_Classic.png"
		},
		"abilities": {
			"lv1_ability": "",
			"lv2_ability": "",
			"lv3_ability": ""
		},
		"summoned_from": {
			"source": "A Sheep once it faints.",
			"url": "https://sapi.com/api/v1/pets/sheep"
		},
		"stats": {
			"lv1_stats": [
				{
					"name": "hp",
					"base_stat": 2,
					"url": "https://sapi.com/api/v1/stats/hp"
				},
				{
					"name": "attack",
					"base_stat": 2,
					"url": "https://sapi.com/api/v1/stats/atk"
				}
			],
			"lv2_stats": [
				{
